#!/usr/bin/env bash
# Script that installs Nginx server on a web server set listing on port 80
sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
