#!/usr/bin/env bash
# Configuring Haproxy Load Balancer
sudo apt update
sudo apt-get install -y haproxy

# Making haproxy to start automaticaly without manual intervention
sudo  echo "ENABLED=1" | sudo tee -a "/etc/default/haproxy"
sudo echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 130100-web-01 54.158.189.235:80 check\n\tserver 130100-web-02 34.202.157.251:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
