#!/usr/bin/env bash
# install load balancer and configures HAproxy
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo -e "\nfrontend http-in" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tbind *:80" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tdefault_backend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\nbackend servers" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 130100-web-01 54.158.189.235:80 check" >> /etc/haproxy/haproxy.cfg
sudo echo -e "\tserver 130100-web-02 34.202.157.251:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
