#!/usr/bin/env bash

# Update the system
sudo apt-get update

# Install HAproxy
sudo apt-get -y install haproxy

# Configure HAproxy to load balance between web-01 and web-02
echo "
frontend http-in
    bind *:80
    default_backend servers

backend servers
    mode http
    balance roundrobin
    server 130100-web-01 54.158.189.235:80 check
    server 130100-web-02 34.202.157.251:80 check
" | sudo tee /etc/haproxy/haproxy.cfg

# Enable HAproxy service
echo "ENABLED=1" | sudo tee /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart
