#!/usr/bin/env bash
#makes my nginx server to listen on port 80 instead of the default 8080

sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
