#!/usr/bin/env bash
# display username, user id and home directory for each line of /etc/passwd.

input="/etc/passwd"
#IFS internal field separator.
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
