#!/usr/bin/env bash
#Contains command used to start apache2 server on a container.
sudo apt-get update
sudo apt-get install curl
sudo apt-get install apache2
cd /var/www/html/
echo "Hello Holberton" > index.html
service apache2 start
service apache2 status